/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'color' : string,
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'itemCount' : bigint,
  'slug' : string,
}
export interface Product {
  'id' : bigint,
  'originalPrice' : number,
  'name' : string,
  'sizes' : Array<string>,
  'discount' : bigint,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'isNew' : boolean,
  'colors' : Array<string>,
  'price' : number,
  'reviewCount' : bigint,
  'isTrending' : boolean,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[string, string], bigint>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      number,
      bigint,
      Array<string>,
      Array<string>,
      boolean,
      boolean,
    ],
    bigint
  >,
  'addToCart' : ActorMethod<[bigint, bigint, string, string], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getWishlist' : ActorMethod<[], Array<Product>>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];