/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'itemCount' : IDL.Nat,
  'slug' : IDL.Text,
});
export const CartItem = IDL.Record({
  'color' : IDL.Text,
  'size' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'originalPrice' : IDL.Float64,
  'name' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'discount' : IDL.Nat,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'isNew' : IDL.Bool,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'isTrending' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'itemCount' : IDL.Nat,
    'slug' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'color' : IDL.Text,
    'size' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'originalPrice' : IDL.Float64,
    'name' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'discount' : IDL.Nat,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'isNew' : IDL.Bool,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };